name: The Eye Site Opticians
favicon: null
layout_spectrum: 0.9804180236533284
typography_spectrum: 0.9200644686352462
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2a4e88'
    - '#b9ccd2'
    - '#6e87ac'
    - '#12b3d1'
  brandStrength: 0.9371688130777329
  lightness: 0.3255675076507032
  saturation: 0.13210633303970098
  rhythmicContrast: 0.7685033972375095
purpose: []
